##employee portal
##employee portal
##employee portal
##Configuration of benifit parameter
##Benifit parameter is defined
##employee asset details
##hr documents
##cost center incharge
##employee change request
##identification document master
##organization master
##travel request
##employee benefit report
##trial user report
##VE usage report
##VE usage trial users
##Workflow
##attendance report
##consolidated leave report
##leave approval workflow
##leave balance report
##pay-days report
##shift pattern master
##short leave quota
##short leave transactions
##team leave report
##average ageing report
##candidate report
##consolidated job report
##joinings report
##parser configuration
##rcm client master
##requisition payout
##relationship management module
##project approval authority
##task backlog report
##task status report
##probation report
##probation level master
##probation report
##annual report
##performance report
##performance review
##track your goals
##discrepancy report
##payout dashboard
##run working days
##upload working days
##wage component master



##my phone numbers
##my emails
##my corrospondances
##add currencies
##recognized
##i want to 


{
'my basic details' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my profile' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my details' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my information' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my info' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my contact details' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my contacts' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my phone number' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my email' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my corrospondance' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'payment info' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'payment information' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'payment info' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'salary account' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'account details' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'my position' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my department' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details',
'my employment' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details',
'my social profiles' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'my social details' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'facebook' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'twitter' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'instagram' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'linkedin' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'address' : 'To view or edit your address, click on My Profile and then head to Address Details.',
'my address' : 'To view or edit your address, click on My Profile and then head to Address Details.',
'residence' : 'To view or edit your address, click on My Profile and then head to Address Details.',
'my manager' : 'To view your Reporting manager and HR manager, click on my profile and then go to Managerial Details.',
'my hr' : 'To view your Reporting manager and HR manager, click on my profile and then go to Managerial Details.',
'my HR' : 'To view your Reporting manager and HR manager, click on my profile and then go to Managerial Details.',
'my assets' : 'To view assets alloted to you, click on my profile and then go to Asset Allotment Details.',
'salary structure' : 'To view your Salary Structure, click on compensation and benifits tab and then go to Salary Structure.',
'my compensation' : 'To view your Salary Structure, click on compensation and benifits tab and then go to Salary Structure.',
'request benefits' : 'To view or request benifits, click on Compensation and Benifits and then go to Request for Benifits.',
'get benefits' : 'To view or request benifits, click on Compensation and Benifits and then go to Request for Benifits.'
'my benefits' : 'To view or request benifits, click on Compensation and Benifits and then go to Request for Benifits.'
'approve benefits' : 'To view or approve benifits request, click on Compensation and Benifits and then go to Approve for Benifits.',
'approve employee benefits': 'To view or approve benifits request, click on Compensation and Benifits and then go to Approve for Benifits.'',
'clear benefits' : 'To view or approve benifits request, click on Compensation and Benifits and then go to Approve for Benifits.',
'assets' : 'To view or create assets, click on Employee Portal and then go to asset categories. Additionally to view or create a sub-category for your asset type, go to Asset Subcategory.',
'asset' : 'To view or create assets, click on Employee Portal and then go to asset categories. Additionally to view or create a sub-category for your asset type, go to Asset Subcategory.',
'employee bands' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'bands' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'band' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'my band' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'blood' : 'To view or create a blood group, click on Employee Portal and then go to Blood Group.',
'bonus' : 'To view or create available bonus types, click on Employee Portal and then go to Bonus.',
'bu' : 'To view or create the business units of your organization, click on Employee Portal and then go to Business Unit.',
'business units' : 'To view or create the business units of your organization, click on Employee Portal and then go to Business Unit.',
'contractor' : 'To view or create a new contractor, click on Employee Portal and then go to Contractor.',
'cost center' : 'To view or create cost center, click on Employee Portal and then go to cost center.',
'cost centre' : 'To view or create cost center, click on Employee Portal and then go to Cost Center.',
'cc' : 'To view or create cost center, click on Employee Portal and then go to Cost Center.',
'country' : 'To view or create country details, click on Employee Portal and then go to Country.',
'currency' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'currencies' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'curr' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'department' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'departments' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'depts' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'dept' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'designation' : 'To view or create designations, click on Employee Portal and then go to Designation.',
'designations' : 'To view or create designations, click on Employee Portal and then go to Designation.',
'desg' : 'To view or create designations, click on Employee Portal and then go to Designation.',
'education' : 'To view, edit or create educational details of employees, click on Employee Portal and then go to Educational Details.',
'edu' : 'To view, edit or create educational details of employees, click on Employee Portal and then go to Educational Details.',
'documents' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'aadhar' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'degree' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'pan' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'PAN' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'ration' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'voter' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'passport' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'expense request' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'expense' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'expenses' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'my expense' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'my expenses' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'approve expenses' : 'To view or approve expense requests of your employees, click on Employee Portal and then go to Employee Expense Approval.',
'approve expense' : 'To view or approve expense requests of your employees, click on Employee Portal and then go to Employee Expense Approval.',
'family' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'family details' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'my family' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'all employees' : 'To view or edit one or more employees, click on Employee Portal and tehn go to Employee.',
'employees' : 'To view or edit one or more employees, click on Employee Portal and then go to Employee.',
'rating' : 'To view, edit or create employee ratings, click on Employee Portal and then go to Employee Rating.',
'ratings' : 'To view, edit or create employee ratings, click on Employee Portal and then go to Employee Rating.',
'referrals' : 'To view, edit or create referral request, click on Employee Portal and then go to Employee Referral Request.',
'referral request' : 'To view, edit or create referral request, click on Employee Portal and then go to Employee Referral Request.',
'referral approval' : 'To approve or reject a referral request, click on Employee Portal and then go to Employee Referral Approval.',
'approve referral' : 'To approve or reject a referral request, click on Employee Portal and then go to Employee Referral Approval.',
'approve a referral' : 'To approve or reject a referral request, click on Employee Portal and then go to Employee Referral Approval.',
'rewards' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'reward' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'recognition' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'recognitions' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'rewards and recognitions' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'language' : 'To view, edit or create languages spoken by employees, click on Employee Portal and then go to Language Master.',
'lang' : 'To view, edit or create languages spoken by employees, click on Employee Portal and then go to Language Master.',
'archived'  : 'To view all employees and their details, click on Employee Portal and then go to Archived Employees.',
'stored' : 'To view all employees and their details, click on Employee Portal and then go to Archived Employees.',
'employee records' : 'To view all employees and their details, click on Employee Portal and then go to Archived Employees.',
'record of employees' : 'To view all employees and their details, click on Employee Portal and then go to Archived Employees.',
'records of employees' : 'To view all employees and their details, click on Employee Portal and then go to Archived Employees.',
'catalogue' : 'To view all employees and their details, click on Employee Portal and then go to Archived Employees.',
'employee log' : 'To view all employees and their details, click on Employee Portal and then go to Archived Employees.',
'hr docs' : '',
'hr documents' : '',
'HR docs' : '',
'HR documents' : '',
'logo' : 'To create a new logo or to view previous logos, click on Employee Portal and then go to Configure Logo',
'cost center incharge' : '',
'asset details' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'assets details' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'details of assets' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'details of asset' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'detail of assets' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'expense reports' : '',
'expense report' : 'To view the expense report of all employees, click on Employee Portal and then go to Expense Report.',
'expenses report' : 'To view the expense report of all employees, click on Employee Portal and then go to Expense Report.',
'report of expenses' : 'To view the expense report of all employees, click on Employee Portal and then go to Expense Report.',
'expenses of employees' : 'To view the expense report of all employees, click on Employee Portal and then go to Expense Report.',
'hired' : 'To enter your details after being hired, click on Employee Portal and then go to Hiring Page.',
'hiring' : 'To enter your details after being hired, click on Employee Portal and then go to Hiring Page.',
'hire' : 'To enter your details after being hired, click on Employee Portal and then go to Hiring Page.',
'transfer' : 'To create request for internal transfer, click on Employee Portal and then go to Internal Transfer Request and to approve a transfer request, click on Employee Portal and then go to Internal Transfer Request Approval. To view the reason for transfer request, click on Employee Portal and then go to Transfer Reason.',
'legal' : 'To view, edit or create a legal entity for your organization, click on Employee Portal and then go to Legal Entity.',
'entity' : 'To view, edit or create a legal entity for your organization, click on Employee Portal and then go to Legal Entity.',
'location' : 'To create a new location, click on Employee Portal and then go to Location.',
'structure' : 'To view the structure of your organization, click on Employee Portal and then go to Organization Structure Maintainance.',
'organization' : 'To view the structure of your organization, click on Employee Portal and then go to Organization Structure Maintainance.',
'announcement' : 'To view, edit or create announcements for your organization, click on Employee Portal and then go to Organization Announcement.',
'announcements' : 'To view, edit or create announcements for your organization, click on Employee Portal and then go to Organization Announcement.',
'type of announcement' : 'To view, edit or create different announcement types, click on Employee Portal and then go to Organisation Announcement Type.',
'types of announcements' : 'To view, edit or create different announcement types, click on Employee Portal and then go to Organisation Announcement Type.',
'type of announcements' : 'To view, edit or create different announcement types, click on Employee Portal and then go to Organisation Announcement Type.',
'types of announcement' : 'To view, edit or create different announcement types, click on Employee Portal and then go to Organisation Announcement Type.',
'pay slip' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'pay slips' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'position' : 'To view, edit or create a new postion for your organization, click on Employee Portal and then go to Position.',
'positions' : 'To view, edit or create a new postion for your organization, click on Employee Portal and then go to Position.',
'qualification' : 'To view or edit previous qualifications or to create a new qualification, click on Employee Portal and then go to Qualification.',
'qual' : 'To view or edit previous qualifications or to create a new qualification, click on Employee Portal and then go to Qualification.',
'qualification' : 'To view or edit previous qualifications or to create a new qualification, click on Employee Portal and then go to Qualification.',
'region' : 'To view or edit previous regions or to create a new region, click on Employee Portal and then go to Region.',
'regions' : 'To view or edit previous regions or to create a new region, click on Employee Portal and then go to Region.',
'reg' : 'To view or edit previous regions or to create a new region, click on Employee Portal and then go to Region.',
'reimbursement' : 'To create a reimbursement request, click on Employee Portal and then go to Reimbursement Request and to approve a rembursement request, click on Employee Portal and then go to Reimbursement Approval.',
'reimb' : 'To create a reimbursement request, click on Employee Portal and then go to Reimbursement Request and to approve a rembursement request, click on Employee Portal and then go to Reimbursement Approval.',
'rembursement' : 'To create a reimbursement request, click on Employee Portal and then go to Reimbursement Request and to approve a rembursement request, click on Employee Portal and then go to Reimbursement Approval.',
'rembersment' : 'To create a reimbursement request, click on Employee Portal and then go to Reimbursement Request and to approve a rembursement request, click on Employee Portal and then go to Reimbursement Approval.',
'category of reimbursement' : 'To create a new reimbursement category, click on Employee Portal and then go to Reimbursement Category Master.',
'reimbursement category' : 'To create a new reimbursement category, click on Employee Portal and then go to Reimbursement Category Master.',
'reimbursement categories' : 'To create a new reimbursement category, click on Employee Portal and then go to Reimbursement Category Master.',
'religion' : 'To view, edit or create religions, click on Employee Portal and then go to Religion.',
'rel' : 'To view, edit or create religions, click on Employee Portal and then go to Religion.',
'sub-department' : 'To view, edit or create a sub-department for your organization, click on Employee Portal and then go to SubDepartment.',
'sub-dept' : 'To view, edit or create a sub-department for your organization, click on Employee Portal and then go to SubDepartment.',
'sub department' : 'To view, edit or create a sub-department for your organization, click on Employee Portal and then go to SubDepartment.',
'sub dept' : 'To view, edit or create a sub-department for your organization, click on Employee Portal and then go to SubDepartment.',
'timesheet' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'time sheets' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'time sheet' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'times sheet' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'work permit' : 'To view, edit or create work permit details, click on Employee Portal and then go to Work Permit.',
'permit for work' : 'To view, edit or create work permit details, click on Employee Portal and then go to Work Permit.',
'visa' : 'To view, edit or create work permit details, click on Employee Portal and then go to Work Permit.',
'guide' : 'To view, edit or create user guide settings, click on Employee Portal and then go to User Guide Settings.',
'bene' : 'To view, edit or create benifits, click on Employee Portal and then go to Benefit Master.',
'benefit' : 'To view, edit or create benifits, click on Employee Portal and then go to Benefit Master.',
'request benefits' : 'To view or create benefits request, click on Employee Portal and then go to Request for Benefits. To approve benefit request, click on Employee Portal and then go to Benefit Requests Approval.',
'benefit request' : 'To view or create benefits request, click on Employee Portal and then go to Request for Benefits. To approve benefit request, click on Employee Portal and then go to Benefit Requests Approval.',
'users' : 'To view the number of users, click on Data Analytics and then go to Active Users Dashboard.',
'number of employees' : 'To view the number of employees classified by location and department, click on Data Analytics and then go to Employees Count.',
'employee count' : 'To view the number of employees classified by location and department, click on Data Analytics and then go to Employees Count.',
'list' : 'To view the list of employees in your organization, click on Data Analytics and then go to Employee List.',
'record' : 'To view the list of employees in your organization, click on Data Analytics and then go to Employee List.',
'directory' : 'To view the list of employees in your organization, click on Data Analytics and then go to Employee List.',
'user guide' : 'To view user guide, click on help and then go to User Guide.',
't&c' : 'To view terms and conditions, click on help and then go to Terms and Conditions.',
'terms and conditions' : 'To view terms and conditions, click on help and then go to Terms and Conditions.',
't and c' : 'To view terms and conditions, click on help and then go to Terms and Conditions.',
'approve in-out' : 'To approve in-out time, click on time management and then go to Approve Manual In-out time.',
'approve time' : 'To approve in-out time, click on time management and then go to Approve Manual In-out time.',
'business travel' : 'To enter a business travel request, click on Time Management and then go to Business Travel Request. To approve a business travel request, click on Time Management and then go to Business Travel Approval.',
'travel for business' : 'To enter a business travel request, click on Time Management and then go to Business Travel Request. To approve a business travel request, click on Time Management and then go to Business Travel Approval.',
'travel due to business' : 'To enter a business travel request, click on Time Management and then go to Business Travel Request. To approve a business travel request, click on Time Management and then go to Business Travel Approval.',
'comp' : 'To view or edit a comp-off request, click on Time  Management and then go to Comp-Off Credit Request. To approve Comp-Off request, click on Time Management and then go to Comp-Off Approval.',
'assignment' : 'To view, edit or create employee group assignments, click on Time Management and then go to Employee Group Assignment.',
'assignments' : 'To view, edit or create employee group assignments, click on Time Management and then go to Employee Group Assignment.',
'group' : 'To view, create or edit employee group or groups, click on Time Management and then go to Employee Group Master. To view, create or edit employee sub-group or sub-groups, click on Time Management and then go to Employee-Sub Group Master.',
'rules' : 'To view, edit or create employee  group rules, click on Time Management and then go to Employee Group Rules.',
'leave quota' : 'To view, edit or create leave quota, click on Time Management and then go to Generate Leave Quota.',
'holidays' : 'To view, edit or add holidays, click on Time Management and then go to Holiday Calender.',
'holiday' : 'To view, edit or add holidays, click on Time Management and then go to Holiday Calender.',
'in-out' : 'To view your in-out time, click on Time Management and then go to In-Out Time.',
'inout' : 'To view your in-out time, click on Time Management and then go to In-Out Time.',
'in out' : 'To view your in-out time, click on Time Management and then go to In-Out Time.',
'leave group' : 'To view, edit or create a leave group, click on Time Management and then go to Leave Group Master.',
'group leave' : 'To view, edit or create a leave group, click on Time Management and then go to Leave Group Master.',
'create leave' : 'To view, edit or create leave types, click on Time Management and then go to Leave Master.',
'create leaves' : 'To view, edit or create leave types, click on Time Management and then go to Leave Master.',
'leave' : 'To apply leaves, click on Time Management and then go to Leave/Time-Off. To approve leaves, click on Time Management and then go to Leave Request Approval.',
'leaves' : 'To apply leaves, click on Time Management and then go to Leave/Time-Off. To approve leaves, click on Time Management and then go to Leave Request Approval.',
'edit in-out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
'reenter in-out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
'edit in out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
're-enter in out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
're-enter in-out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
'allocate' : 'To view allocated shifts, click on Time Management and then go to Shift Details. To allocate shifts, click on Time Management and then go to Shift Allocation.',
'allocation' : 'To view allocated shifts, click on Time Management and then go to Shift Details. To allocate shifts, click on Time Management and then go to Shift Allocation.',
'assign' : 'To view allocated shifts, click on Time Management and then go to Shift Details. To allocate shifts, click on Time Management and then go to Shift Allocation.',
'assigned' : 'To view allocated shifts, click on Time Management and then go to Shift Details. To allocate shifts, click on Time Management and then go to Shift Allocation.',
'create shift' : 'To create a new shift, click on Time Management and then go to Shift Master.',
'create shifts' : 'To create a new shift, click on Time Management and then go to Shift Master.',
'new shift' : 'To create a new shift, click on Time Management and then go to Shift Master.',
'add a candidate' : 'To view, add or modify candidates shortlisted, click on Talent Management and then go to Add/Modify Candidates.',
'modify candidate' : 'To view, add or modify candidates shortlisted, click on Talent Management and then go to Add/Modify Candidates.',
'modify candidates' : 'To view, add or modify candidates shortlisted, click on Talent Management and then go to Add/Modify Candidates.',
'add/modify candidate' : 'To view, add or modify candidates shortlisted, click on Talent Management and then go to Add/Modify Candidates.',
'add candidates' : 'To view, add or modify candidates shortlisted, click on Talent Management and then go to Add/Modify Candidates.', 
'add candidate' : 'To view, add or modify candidates shortlisted, click on Talent Management and then go to Add/Modify Candidates.',
'add a candidate' : 'To view, add or modify candidates shortlisted, click on Talent Management and then go to Add/Modify Candidates.',
'client' : 'To see the status of external clients, click on Talent Management and then go to External Client Status.',
'clients' : 'To see the status of external clients, click on Talent Management and then go to External Client Status.',
'interview' : 'To view, edit or give ratings to candidates, click on Talent Management and then go to Interview Rating.',
'schedule' : 'To schedule interview with candidates, click on Talent Management and then go to Schedule Interview.',
'requisition' : 'To view, edit or create job requisition, click on Talent Management and then go to Job Requisition. To approve job requisition, click on Talent Management and then go to Requisition Approval.',
'loi' : 'To view, edit or create Letter of Intent, click on Talent Management and then go to LOI Template.',
'letter' : 'To view, edit or create Letter of Intent, click on Talent Management and then go to LOI Template.',
'offer' : 'To approve or reject a job offer, click on Talent Management and then go to Offer Approval.',
'posted' : 'To view or edit posted jobs, click on Talent Management and then go to Posted Job.',
'stats' : 'To view or edit recruitment statistics, click on Talent Management and then go to Recruitment Dashboard.',
'statistics' : 'To view or edit recruitment statistics, click on Talent Management and then go to Recruitment Dashboard.',
'resumes' : 'To upload resumes, click on Talent Management and then go to Resume Bulk Upload.',
'resume' : 'To upload resumes, click on Talent Management and then go to Resume Bulk Upload.',
'tenure' : 'To view, create or edit tenures, click on Talent Management and then go to Tenure Master.',
'tenures' : 'To view, create or edit tenures, click on Talent Management and then go to Tenure Master.',
'repo' : 'To set a repository for resumes, click on Talent Management and then go to Resume Repository Configuration.',
'repository' : 'To set a repository for resumes, click on Talent Management and then go to Resume Repository Configuration.',
'resignation' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'resign' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'terminate' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'termination' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'firing' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'fire' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'seperation' : 'To configure seperation process, click on Seperation and then click on Seperation Configuration.',
'purchase' : 'To view, edit or create a purchase order, click on Purchase Order Management and then go to Item Master.',
'purchase order approval' : 'To approve purchase order, click on Purchase Order Management and then go to Purchase Approval HR.',
'approve purchase order' : 'To approve purchase order, click on Purchase Order Management and then go to Purchase Approval HR.',
'attach' : 'To attach files to your purchase order, click on Purchase Order Management and then go to Purchase Order Attachments.',
'attachment' : 'To attach files to your purchase order, click on Purchase Order Management and then go to Purchase Order Attachments.',
'purchase order request' : 'To create a request for purchase order, click on Purchase Order Management and then go to Purchase Request.',
'request for purchase order' : 'To create a request for purchase order, click on Purchase Order Management and then go to Purchase Request.',
'task assignment' : 'To assign task, click on Project Management and then go to Assign Task.',
'assign task' : 'To assign task, click on Project Management and then go to Assign Task.',
'assign tasks' : 'To assign task, click on Project Management and then go to Assign Task.',
'to do' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'to-do' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'task' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'tasks' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'project' : 'To view, edit or create your project assets or verticals, click on Project Management and then go to Project Vertical.',
'project timeline' : 'To create your project workflow, click on Project Management and then go to Project Workflow Request.',
'project workflow' : 'To create your project workflow, click on Project Management and then go to Project Workflow Request.',
'backlog' : 'To view your task backlog, click on Project Management and then go to Task Backlog.',
'delay in task' : 'To view your task backlog, click on Project Management and then go to Task Backlog.',
'delay in tasks' : 'To view your task backlog, click on Project Management and then go to Task Backlog.',
'task delay' : 'To view your task backlog, click on Project Management and then go to Task Backlog.',
'all tasks' : 'To view all tasks, click on Project Management and then go to Task List Details.',
'task details' : 'To view all tasks, click on Project Management and then go to Task List Details.',
'probation' : 'To create a new probation group, click on Probation and then go to Employee Probation Group Master.',
'confirmation': 'To generate confirmation letter, go to Probation and then click on Generate Confirmation Letter.',
'probation approval': 'To give probation approval, click on Probation and then go to Probation Approval.'
'approve after probation': 'To give probation approval, click on Probation and then go to Probation Approval.'
'approve an employee after probation': 'To give probation approval, click on Probation and then go to Probation Approval.'
'approve probation': 'To give probation approval, click on Probation and then go to Probation Approval.'
'probation workflow': 'To set a probation approval workflow, click on Probation and then go to Probation Approval Workflow Configuration.'
'probation approval workflow': 'To set a probation approval workflow, click on Probation and then go to Probation Approval Workflow Configuration.'
'probation period': 'To set a probation period in months, click on Probation and then go to Probation Period Master.'
'duration of probation': 'To set a probation period in months, click on Probation and then go to Probation Period Master.'
'period of probation': 'To set a probation period in months, click on Probation and then go to Probation Period Master.'
'probation duration': 'To set a probation period in months, click on Probation and then go to Probation Period Master.'
'probation time': 'To set a probation period in months, click on Probation and then go to Probation Period Master.'
'time of probation': 'To set a probation period in months, click on Probation and then go to Probation Period Master.'
'goals': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'targets': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'goal': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'target': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'plan': 'To make a plan to accomplish targets, click on Performance Management and then got to Goal Plan Master.',
'plans': 'To make a plan to accomplish targets, click on Performance Management and then got to Goal Plan Master.',
'goal records': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'previous goals': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'a previous goal': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'target records': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'goals library': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'targets library': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'goal record': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'target record': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'track my goals': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'track my targets': 'To view previous goal records, click on Performance Management and then go to Goals Library.',
'investment': 'To view, edit or create your investment declaration, click on Payroll and then go to Employee Investment Declaration.',
'arrear': 'To view your arrear details, click on Payroll and then go to Arrear Payment.',
'block payroll': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'block the payroll': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'payroll blocking': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'blocking payroll': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'stop payroll': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'end payroll': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'stop the payroll': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'end the payroll': 'To block the payroll of an employee, click on Payroll and then go to Block Employee Payroll.',
'ctc': 'To view, edit or create employee CTC details, click on Payroll and then go to Employee CTC.',
'pay': 'To view, edit or create employee CTC details, click on Payroll and then go to Employee CTC.',
'salary': 'To view, edit or create employee CTC details, click on Payroll and then go to Employee CTC.',
'approve declaration': 'To approve employee declaration, click on Payroll and then go to Employee Declaration Approval.',
'declaration approval': 'To approve employee declaration, click on Payroll and then go to Employee Declaration Approval.',
'declaration form': 'To access employee declaration form, click on Payroll and then go to Employee Declaration Form.',
'declare policies': 'To access employee declaration form, click on Payroll and then go to Employee Declaration Form.',
'my deductions': 'To view employee deductions, click on Payroll and then go to Employee Deduction.',
'my deduction': 'To view employee deductions, click on Payroll and then go to Employee Deduction.',
'employee deductions': 'To view employee deductions, click on Payroll and then go to Employee Deduction.',
'employee deduction': 'To view employee deductions, click on Payroll and then go to Employee Deduction.',
'deductions of employees': 'To view employee deductions, click on Payroll and then go to Employee Deduction.',
'deduction of employee': 'To view employee deductions, click on Payroll and then go to Employee Deduction.',
'deductions of employee': 'To view employee deductions, click on Payroll and then go to Employee Deduction.',
'employee payslip': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'payslip of employees': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'payslip of all employees': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'payslip of all the employees': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'payslips of all the employees': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'payslips of all employees': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'payslips of employees': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'employee payslips': 'To view payslips of all the employees, click on Payroll and then go to Employee Payslips.',
'pf': 'To view provident fund details of employees, click on Payroll and then go to Employee PF Account Details.',
'provident': 'To view provident fund details of employees, click on Payroll and then go to Employee PF Account Details.',
'previous': 'To view employees previous income details, click on payroll and then go to Employee Previous Income.' ,
'extra income': 'To declare your extra income, click on Payroll and then go to Extra Income Declaration.',
'extra pay': 'To declare your extra income, click on Payroll and then go to Extra Income Declaration.',
'extra salary': 'To declare your extra income, click on Payroll and then go to Extra Income Declaration.',
'form 16': 'To create, edit or view form 16 of employees, click on Payroll and then go to Form 16.',
'form16': 'To create, edit or view form 16 of employees, click on Payroll and then go to Form 16.',
'incentive': 'To create, edit or view your incentive details, click on Payroll and then go to Incentive Payment.',
'it': 'To view, edit or create IT Declaration details, click on  Payroll and then go to IT Declaration CutOff.',
'IT': 'To view, edit or create IT Declaration details, click on  Payroll and then go to IT Declaration CutOff.',
'income tax': 'To view, edit or create IT Declaration details, click on  Payroll and then go to IT Declaration CutOff.',
'monthly': 'To create, edit or view monthly tax declaration, click on Payroll and then go to Monthly Tax Declaration.',
'frequency': 'To set a pay frequency, click on Payroll and then go to Pay Frequency Master.',
'variable': 'To enter variable component for an employee, click on Payroll and then go to Payroll component.',
'variable pay': 'To enter variable component for an employee, click on Payroll and then go to Payroll component.',
'payroll': 'To create an employee payroll group, click on Payroll and then go to Payroll Employee Group.',
'run payroll': 'To run the payroll, click on Payroll and then go to Run Payroll.',
'final salary': 'To run the payroll, click on Payroll and then go to Run Payroll.',
'salary breakup': 'To view your salary breakup, click on Payroll and then go to Salary Breakup.',
'seperation settings': 'To create, view or edit employee seperation settings, click on Payroll and then go to Seperation Settings.',
'set tax rates': 'To create, view or edit tax rates, click on Payroll and then go to Tax Rate Master.'
}

my_dict = {
'my payment info' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'my payment information' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'my salary account' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'my account details' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'my facebook' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'my twitter' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'my instagram' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'my linkedin' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'my residence' : 'To view or edit your address, click on My Profile and then head to Address Details.'
'my salary structure' : 'To view your Salary Structure, click on compensation and benifits tab and then go to Salary Structure.',
'my request benifits' : 'To view or request benifits, click on Compensation and Benifits and then go to Request for Benifits.',
'my assets' : 'To view or create assets, click on Employee Portal and then go to asset categories. Additionally to view or create a sub-category for your asset type, go to Asset Subcategory.',
'my asset' : 'To view or create assets, click on Employee Portal and then go to asset categories. Additionally to view or create a sub-category for your asset type, go to Asset Subcategory.',
'my band' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'my blood' : 'To view or create a blood group, click on Employee Portal and then go to Blood Group.',
'my bonus' : 'To view or create available bonus types, click on Employee Portal and then go to Bonus.',
'my contractor' : 'To view or create a new contractor, click on Employee Portal and then go to Contractor.',
'my country' : 'To view or create country details, click on Employee Portal and then go to Country.',
'my currency' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'my currencies' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'my curr' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'my department' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'my departments' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'my depts' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'my dept' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'my designation' : 'To view or create designations, click on Employee Portal and then go to Designation.',
'my desg' : 'To view or create designations, click on Employee Portal and then go to Designation.',
'my education' : 'To view, edit or create educational details of employees, click on Employee Portal and then go to Educational Details.',
'my edu' : 'To view, edit or create educational details of employees, click on Employee Portal and then go to Educational Details.',
'my documents' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my aadhar' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my degree' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my pan' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my PAN' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my ration' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my voter' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my passport' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'my expense request' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'my expense' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'my expenses' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'my family' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'my family details' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'my employees' : 'To view or edit one or more employees, click on Employee Portal and then go to Employee.',
'my rating' : 'To view, edit or create employee ratings, click on Employee Portal and then go to Employee Rating.',
'ratings' : 'To view, edit or create employee ratings, click on Employee Portal and then go to Employee Rating.',
'my referrals' : 'To view, edit or create referral request, click on Employee Portal and then go to Employee Referral Request.',
'my referral request' : 'To view, edit or create referral request, click on Employee Portal and then go to Employee Referral Request.',
'my rewards' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'my reward' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'my recognition' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'my recognitions' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'my rewards and recognitions' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details. To view rewards and recognition details click on Employee Portal and then go to RNR Details.',
'my language' : 'To view, edit or create languages spoken by employees, click on Employee Portal and then go to Language Master.',
'my lang' : 'To view, edit or create languages spoken by employees, click on Employee Portal and then go to Language Master.',
'hr docs' : '',
'hr documents' : '',
'HR docs' : '',
'HR documents' : '',
'logo' : 'To create a new logo or to view previous logos, click on Employee Portal and then go to Configure Logo',
'cost center incharge' : '',
'my asset details' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'my assets details' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'my details of assets' : 'To view, edit or create assets under different employees, click on Employee Portal and then go to Employee Asset Details.',
'my expense report' : 'To view the expense report of all employees, click on Employee Portal and then go to Expense Report.',
'my expenses report' : 'To view the expense report of all employees, click on Employee Portal and then go to Expense Report.',
'my pay slip' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'my pay slips' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'my payslips' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'my payslip' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'payslip' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'payslips' : 'To view or download your payslip(s), click on Employee Portal and then go to Pay Slips.',
'my position' : 'To view, edit or create a new postion for your organization, click on Employee Portal and then go to Position.',
'my qualification' : 'To view or edit previous qualifications or to create a new qualification, click on Employee Portal and then go to Qualification.',
'my qual' : 'To view or edit previous qualifications or to create a new qualification, click on Employee Portal and then go to Qualification.',
'my qualification' : 'To view or edit previous qualifications or to create a new qualification, click on Employee Portal and then go to Qualification.',
'my religion' : 'To view, edit or create religions, click on Employee Portal and then go to Religion.',
'my rel' : 'To view, edit or create religions, click on Employee Portal and then go to Religion.',
'my timesheet' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'my time sheets' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'my time sheet' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'my times sheet' : 'To view, edit or create tasks assigned to you, click on Employee Portal and then go to Timesheet.',
'my work permit' : 'To view, edit or create work permit details, click on Employee Portal and then go to Work Permit.',
'my permit for work' : 'To view, edit or create work permit details, click on Employee Portal and then go to Work Permit.',
'my visa' : 'To view, edit or create work permit details, click on Employee Portal and then go to Work Permit.',
'my bene' : 'To view, edit or create benifits, click on Employee Portal and then go to Benefit Master.',
'my benefit' : 'To view, edit or create benifits, click on Employee Portal and then go to Benefit Master.',
'request benefits' : 'To view or create benefits request, click on Employee Portal and then go to Request for Benefits. To approve benefit request, click on Employee Portal and then go to Benefit Requests Approval.',
'my benefit request' : 'To view or create benefits request, click on Employee Portal and then go to Request for Benefits. To approve benefit request, click on Employee Portal and then go to Benefit Requests Approval.',
'my assignment' : 'To view, edit or create employee group assignments, click on Time Management and then go to Employee Group Assignment.',
'my assignments' : 'To view, edit or create employee group assignments, click on Time Management and then go to Employee Group Assignment.',
'my holidays' : 'To view, edit or add holidays, click on Time Management and then go to Holiday Calender.',
'holiday' : 'To view, edit or add holidays, click on Time Management and then go to Holiday Calender.',
'my in-out' : 'To view your in-out time, click on Time Management and then go to In-Out Time.',
'my inout' : 'To view your in-out time, click on Time Management and then go to In-Out Time.',
'my in out' : 'To view your in-out time, click on Time Management and then go to In-Out Time.',
'my leave' : 'To apply leaves, click on Time Management and then go to Leave/Time-Off. To approve leaves, click on Time Management and then go to Leave Request Approval.',
'my leaves' : 'To apply leaves, click on Time Management and then go to Leave/Time-Off. To approve leaves, click on Time Management and then go to Leave Request Approval.',
'edit my in-out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
'reenter my in-out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
'edit my in out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
're-enter my in out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
're-enter my in-out' : 'To manually enter in-out time, click on Time Management and then go to Manual In-Out Time.',
'my client' : 'To see the status of external clients, click on Talent Management and then go to External Client Status.',
'my clients' : 'To see the status of external clients, click on Talent Management and then go to External Client Status.',
'my resignation' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'my resign' : 'To submit resignation request, click on Seperation and then go to Resignation Request. To approve Resignation/Termination, click on Seperation and then go to Resignation/Termination Approval.',
'my to do' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'my to-do' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'my task' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'my tasks' : 'To see your to-do task, click on Project Management and then go to My to do task.',
'my task details' : 'To view all tasks, click on Project Management and then go to Task List Details.',
'my goals': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'my targets': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'my goal': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'my target': 'To set a new target, click on Performance Management and then go to Assign New Goals.',
'my plan': 'To make a plan to accomplish targets, click on Performance Management and then got to Goal Plan Master.',
'my plans': 'To make a plan to accomplish targets, click on Performance Management and then got to Goal Plan Master.',
'my ctc': 'To view, edit or create employee CTC details, click on Payroll and then go to Employee CTC.',
'my pay': 'To view, edit or create employee CTC details, click on Payroll and then go to Employee CTC.',
'my salary': 'To view, edit or create employee CTC details, click on Payroll and then go to Employee CTC.',
'my pf': 'To view provident fund details of employees, click on Payroll and then go to Employee PF Account Details.',
'my provident': 'To view provident fund details of employees, click on Payroll and then go to Employee PF Account Details.',
'my previous': 'To view employees previous income details, click on payroll and then go to Employee Previous Income.' ,
'my extra income': 'To declare your extra income, click on Payroll and then go to Extra Income Declaration.',
'my extra pay': 'To declare your extra income, click on Payroll and then go to Extra Income Declaration.',
'my extra salary': 'To declare your extra income, click on Payroll and then go to Extra Income Declaration.',
'my form 16': 'To create, edit or view form 16 of employees, click on Payroll and then go to Form 16.',
'my form16': 'To create, edit or view form 16 of employees, click on Payroll and then go to Form 16.',
'my incentive': 'To create, edit or view your incentive details, click on Payroll and then go to Incentive Payment.',
'my it': 'To view, edit or create IT Declaration details, click on  Payroll and then go to IT Declaration CutOff.',
'my IT': 'To view, edit or create IT Declaration details, click on  Payroll and then go to IT Declaration CutOff.',
'my income tax': 'To view, edit or create IT Declaration details, click on  Payroll and then go to IT Declaration CutOff.',
'my monthly': 'To create, edit or view monthly tax declaration, click on Payroll and then go to Monthly Tax Declaration.',
'my variable': 'To enter variable component for an employee, click on Payroll and then go to Payroll component.',
'my variable pay': 'To enter variable component for an employee, click on Payroll and then go to Payroll component.',
'my payroll': 'To create an employee payroll group, click on Payroll and then go to Payroll Employee Group.',
'my final salary': 'To run the payroll, click on Payroll and then go to Run Payroll.',
'my salary breakup': 'To view your salary breakup, click on Payroll and then go to Salary Breakup.',
'my seperation settings': 'To create, view or edit employee seperation settings, click on Payroll and then go to Seperation Settings.',
} 