{
'my basic details' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my profile' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my details' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my information' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my info' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my contact details' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my contacts' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my phone number' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my email' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'my corrospondance' : 'To view or edit your Contact Details, click on My Profile and then head to Contacts.',
'payment info' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'payment information' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'payment info' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'salary account' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'account details' : 'To view or edit details of your salary account, click on My Profile and then head to Payment Information.',
'my position' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details.',
'my department' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details',
'my employment' : 'To view or edit your basic details, click on My Profile and then head to Basic. For employment details, head to Employee Details. For medical and other details, head to Personal Details',
'my social profiles' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'my social details' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'facebook' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'twitter' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'instagram' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'linkedin' : 'To view or edit your basic details, click on My Profile and then head to Social Details.',
'address' : 'To view or edit your address, click on My Profile and then head to Address Details.',
'my address' : 'To view or edit your address, click on My Profile and then head to Address Details.',
'residence' : 'To view or edit your address, click on My Profile and then head to Address Details.',
'my manager' : 'To view your Reporting manager and HR manager, click on my profile and then go to Managerial Details.',
'my hr' : 'To view your Reporting manager and HR manager, click on my profile and then go to Managerial Details.',
'my HR' : 'To view your Reporting manager and HR manager, click on my profile and then go to Managerial Details.',
'my assets' : 'To view assets alloted to you, click on my profile and then go to Asset Allotment Details.',
'salary structure' : 'To view your Salary Structure, click on compensation and benifits tab and then go to Salary Structure.',
'my compensation' : 'To view your Salary Structure, click on compensation and benifits tab and then go to Salary Structure.',
'request benifits' : 'To view or request benifits, click on Compensation and Benifits and then go to Request for Benifits.',
'get benifits' : 'To view or request benifits, click on Compensation and Benifits and then go to Request for Benifits.',
'my benifits' : 'To view or request benifits, click on Compensation and Benifits and then go to Request for Benifits.',
'approve benifits' : 'To view or approve benifits request, click on Compensation and Benifits and then go to Approve for Benifits.',
'clear benifits' : 'To view or approve benifits request, click on Compensation and Benifits and then go to Approve for Benifits.',
'assets' : 'To view or create assets, click on Employee Portal and then go to asset categories. Additionally to view or create a sub-category for your asset type, go to Asset Subcategory.',
'asset' : 'To view or create assets, click on Employee Portal and then go to asset categories. Additionally to view or create a sub-category for your asset type, go to Asset Subcategory.',
'employee bands' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'bands' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'band' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'my band' : 'To view or create employee bands, click on Employee Portal and then go to Band.',
'blood' : 'To view or create a blood group, click on Employee Portal and then go to Blood Group.',
'bonus' : 'To view or create available bonus types, click on Employee Portal and then go to Bonus.',
'bu' : 'To view or create the business units of your organization, click on Employee Portal and then go to Business Unit.',
'business units' : 'To view or create the business units of your organization, click on Employee Portal and then go to Business Unit.',
'contractor' : 'To view or create a new contractor, click on Employee Portal and then go to Contractor.',
'cost center' : 'To view or create cost center, click on Employee Portal and then go to cost center.',
'cost centre' : 'To view or create cost center, click on Employee Portal and then go to Cost Center.',
'cc' : 'To view or create cost center, click on Employee Portal and then go to Cost Center.',
'country' : 'To view or create country details, click on Employee Portal and then go to Country.',
'currency' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'currencies' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'curr' : 'To view or create currencies, click on Employee Portal and then go to Currency.',
'department' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'departments' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'depts' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.',
'dept' : 'To view existing departments or to create new departments, click on Employee Portal and then go to Department.', 
'designation' : 'To view or create designations, click on Employee Portal and then go to Designation.',
'desg' : 'To view or create designations, click on Employee Portal and then go to Designation.',
'education' : 'To view, edit or create educational details of employees, click on Employee Portal and then go to Educational Details.',
'edu' : 'To view, edit or create educational details of employees, click on Employee Portal and then go to Educational Details.',
'documents' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'aadhar' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'degree' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'pan' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'PAN' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'ration' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'voter' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'passport' : 'To view, edit or create documents for employees, click on Employee Portal and then go to Employee Document Details.',
'expense request' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'expense' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'expenses' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'my expense' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'my expenses' : 'To view or create your expense request, click on Employee Portal and then go to Employee Expense Request.',
'approve expenses' : 'To view or approve expense requests of your employees, click on Employee Portal and then go to Employee Expense Approval.',
'approve expense' : 'To view or approve expense requests of your employees, click on Employee Portal and then go to Employee Expense Approval.',
'family' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'family details' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'my family' : 'To view, edit or create family details, click on Employee Portal and then go to Employee Family Details.',
'all employees' : 'To view or edit one or more employees, click on Employee Portal and tehn go to Employee.',
'employees' : 'To view or edit one or more employees, click on Employee Portal and then go to Employee.',
'rating' : 'To view, edit or create employee ratings, click on Employee Portal and then go to Employee Rating.',
'ratings' : 'To view, edit or create employee ratings, click on Employee Portal and then go to Employee Rating.',
'referrals' : 'To view, edit or create referral request, click on Employee Portal and then go to Employee Referral Request.',
'referral request' : 'To view, edit or create referral request, click on Employee Portal and then go to Employee Referral Request.',
'referral approval' : 'To approve or reject a referral request, click on Employee Portal and then go to Employee Referral Approval.',
'approve referral' : 'To approve or reject a referral request, click on Employee Portal and then go to Employee Referral Approval.',
'rewards' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details.',
'reward' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details.',
'recognition' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details.',
'recognitions' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details.',
'rewards and recognitions' : 'To view, edit or create a rewards and recognitions category, click on Employee Portal and then go to Rewards and Reconigtions Details.',
'language' : 'To view, edit or create languages spoken by employees, click on Employee Portal and then go to Language Details.',
'lang' : 'To view, edit or create languages spoken by employees, click on Employee Portal and then go to Language Details.',
}
 